### ISSUE TITLE
Does not install on Ubuntu 18.04

### ISSUE THREAD

**Issue by StuartMacKay** [Kronopt/SimulATe#1] opened 2019-07-06 11:29 UTC
I followed the instructions in the README. At first I created a virtualenv and tried to install kivy - that failed when building the wheel. I deleted the virtualenv. Next I installed the kivy package for Ubuntu. That worked but when running SimulATe a blank window appears and promptly closes.

Here are the commands I ran to install and run the app.

```sh
sudo apt-get update
sudo apt-get install python-kivy
sudo apt-get install xclip xsel

git clone git@github.com:Kronopt/SimulATe.git

cd SimulATe
python2.7 SimulATe.pyw
```
xclip and xsel were not included. I install those after reading https://github.com/kivy/kivy/issues/4764

The console output when running SimulATe was:

```
[INFO   ] [Logger      ] Record log in /home/stuart/.kivy/logs/kivy_19-07-06_5.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 19.0.2>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [WARNING     ] bin/ui/dynamic_classes.kv has already been included!
[WARNING] [WARNING     ] bin/ui/dynamic_classes.kv has already been included!
[WARNING] [WARNING     ] bin/ui/dynamic_classes.kv has already been included!
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
```
Here is the [errorlog.txt](https://github.com/Kronopt/SimulATe/files/3364638/errorlog.txt)

Details of the packages installed:
```
python-kivy_1.9.1-1build3_amd64.deb
xclip_0.12+svn84-4build1_amd64.deb
xsel_1.2.0-4_amd64.deb
```
Ubuntu version (running lsb_release -a):
```
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by Kronopt** [comment] 2019-07-06 12:55
Hi.
I'll try to address your problem in the coming days.
The problem is probably be related with the dependencies...

**Comment by Kronopt** [comment] 2019-07-08 14:39
So, yeah, the problem is with the Kivy dependencies...
I booted a fresh Ubuntu 18.04 install in a virtual machine, downloaded this repo and installed Kivy through conda, and it worked.

Installing the precompiled Kivy wheels does not work.
Installing Kivy as a software package (ppa) does not work.

So I recommend installing through conda, like so:
* Install [miniconda](https://docs.conda.io/en/latest/miniconda.html)
* run ```conda install kivy -c conda-forge```

I'm going to update the README.
Please tell me if this solves the issue for you.

**Comment by StuartMacKay** [comment] 2019-07-08 15:48
Installing using conda worked. There is an exception thrown on startup:
```sh
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - OSError: [Errno 2] No such file or directory
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

xsel - OSError: [Errno 2] No such file or directory
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/stuart/anaconda3/envs/sim/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

```
However that does not appear to affect the running of the program.

Thanks for the quick reply and thanks for this project.

**Comment by Kronopt** [comment] 2019-07-08 16:39
That new error seems to be related with xclip and xsel.
I didn't install those directly, so, if they are needed, they should be installed through conda.

Try to uninstall xclip and xsel.
After, maybe reinstall kivy through conda

**Comment by Kronopt** [comment] 2019-07-10 10:33
As the main issue as been resolved, I'm closing this.
Feel free to comment if you're still having problems

**Closed as completed by Kronopt** 2019-07-10 10:33 UTC
